### PR TITLE
Updated to collect dpkg.log and verify installed files. Also, search for package name that contains installed files.

### PR DESCRIPTION
**Pull request by mnrkbys**
Added an artifact to collect /var/log/dpkg.log to artifacts/files/packages/dpkg.yaml.
Added an artifact to verify files installed from dpkg package. This is similar to the "rpm -q -a" command in artifacts/live_response/packages/dpkg.yaml.

And I also added artifacts that search for packages that contain installed files. Files not included in a package may have been installed manually, helping to find suspect files.
As you know, /bin is a symbolic link to /usr/bin. Therefore, whether the installation destination directory is /bin or /usr/bin, the files are installed in the same directory.
However, "dpkg -S /bin/ls" and "dpkg -S /usr/bin/ls" return different results. Therefore, "dpkg -S" must be executed for both file paths.

"dpkg -S /bin/ls" vs "dpkg -S /usr/bin/ls"

```
$ dpkg -S /bin/ls
coreutils: /bin/ls
$ dpkg -S /usr/bin/ls
dpkg-query: no path found matching pattern /usr/bin/ls
```

But, "rpm -q -f" will returns same results.
"rpm -q -f /bin/ls" vs "rpm -q -f /usr/bin/ls"

```
$ rpm -q -f /bin/ls
coreutils-8.32-35.el9.x86_64
$ rpm -q -f /usr/bin/ls
coreutils-8.32-35.el9.x86_64
```

### CODE REVIEW

**Comment by tclahr** [comment]
Do you know if we can do the same for additional package managers such as pacman, brew, zipper...?

**Comment by mnrkbys** [comment]
I've tried `zypper` on openSUSE, and the results are like below.

```
> zypper --quiet search --provides --match-exact --installed-only /usr/bin/ls

S  | Name      | Summary            | Type
---+-----------+--------------------+--------
i  | coreutils | GNU Core Utilities | package
> zypper --quiet search --provides --match-exact --installed-only /bin/ls

S  | Name      | Summary            | Type
---+-----------+--------------------+--------
i  | coreutils | GNU Core Utilities | package
> zypper --quiet search --provides --match-exact --installed-only /nonexistent/file
No matching items found.
```

I believe zypper can check file paths as well as dpkg/rpm.
However, files under `/usr/sbin/` will show different results for the paths `/sbin/` and `/usr/sbin/`.

```
> zypper --quiet search --provides --match-exact --installed-only /sbin/bpftool 
No matching items found.
> zypper --quiet search --provides --match-exact --installed-only /usr/sbin/bpftool 

S  | Name    | Summary                                                       | Type
---+---------+---------------------------------------------------------------+--------
i+ | bpftool | Tool for inspection and manipulation of BPF programs and maps | package
```

**Comment by mnrkbys** [comment]
I have found a useful table.
This includes package management commands for various distributions (except `brew`).

pacman/Rosetta - ArchWiki
https://wiki.archlinux.org/title/Pacman/Rosetta

**Comment by mnrkbys** [comment]
As for `brew`, it does not seem to have the same functionality.
However, you can get a list of files included in a package with `list -v <package_name>`, so we may be able to find files not included in installed packages by comparing the list with files under `/opt/homebrew/bin`.

**Comment by tclahr** [comment]
I did some tests on some debian (dpkg), redhat (rpm) and arch (pacman) based systems and the collection time was increased by approximately 10 to 15 min in some situations.
The command to check whether a file belongs to an installed package is very costly (consumes a lot of resources).

Also, it seems that `dpkg -S` reports a lot of false-positives. Look at the samples below.

From Ubuntu 22.04:
```$ cd /bin && for file in *; do dpkg -S "${file}"; done 2>&1 | grep "no path found"```
```
dpkg-query: no path found matching pattern [
dpkg-query: no path found matching pattern *gnome-text-editor*
dpkg-query: no path found matching pattern *gnome-www-browser*
dpkg-query: no path found matching pattern *gstreamer-codec-install*
dpkg-query: no path found matching pattern *i686-linux-gnu-pkg-config*
dpkg-query: no path found matching pattern *infobrowser*
dpkg-query: no path found matching pattern *lzcat*
dpkg-query: no path found matching pattern *lzcmp*
dpkg-query: no path found matching pattern *lzdiff*
dpkg-query: no path found matching pattern *lzegrep*
dpkg-query: no path found matching pattern *lzfgrep*
dpkg-query: no path found matching pattern *lzgrep*
dpkg-query: no path found matching pattern *lzless*
dpkg-query: no path found matching pattern *lzmore*
dpkg-query: no path found matching pattern *nawk*
dpkg-query: no path found matching pattern *pinentry-x11*
dpkg-query: no path found matching pattern *test123*
dpkg-query: no path found matching pattern *x86_64-linux-gnu-pkg-config*
dpkg-query: no path found matching pattern *x-session-manager*
dpkg-query: no path found matching pattern *x-terminal-emulator*
dpkg-query: no path found matching pattern *x-www-browser*
```

During my tests I did not notice lots of false positives for `rpm -q -f` on Fedora/Red Hat based systems, but as most binaries were not installed by rpm in AIX, it does report lots of false-positives.

From AIX 7.3:
```$ cd /usr/bin && for file in *; do rpm -q -f "${file}" | sed "s|$|: ${file}|"; done | grep "not owned"```
```
file /usr/bin/2to3 is not owned by any package: 2to3
file /usr/bin/2to3-3.9 is not owned by any package: 2to3-3.9
file /usr/bin/IbDebugChk is not owned by any package: IbDebugChk
file /usr/bin/IbDebugOff is not owned by any package: IbDebugOff
file /usr/bin/IbDebugOn is not owned by any package: IbDebugOn
file /usr/bin/Mail is not owned by any package: Mail
file /usr/bin/ManGetURL.class is not owned by any package: ManGetURL.class
file /usr/bin/Rsh is not owned by any package: Rsh
file /usr/bin/SpmiArmd is not owned by any package: SpmiArmd
file /usr/bin/SpmiResp is not owned by any package: SpmiResp
file /usr/bin/X11 is not owned by any package: X11
file /usr/bin/X11r5 is not owned by any package: X11r5
file /usr/bin/X11r6 is not owned by any package: X11r6
file /usr/bin/[ is not owned by any package: [
file /usr/bin/acctcom is not owned by any package: acctcom
file /usr/bin/acctctl is not owned by any package: acctctl
file /usr/bin/acctras is not owned by any package: acctras
file /usr/bin/acctrpt is not owned by any package: acctrpt
file /usr/bin/aclconvert is not owned by any package: aclconvert
...
...
```

As the `hash_executables.yaml` artifact can be used to identify malicious files, I will create a different yaml file for this, but not add it to any profile. It will be available to be run as needed. I will commit to this PR and send it for your review.

Thanks a lot!

**Comment by mnrkbys** [comment]
Thanks for testing this.
Indeed, I should have mentioned that the command takes a long time to execute.

**Comment by tclahr** [comment]
@mnrkbys can you review the changes, please?

**Comment by mnrkbys** [comment]
Thanks @tclahr 
It appears to me that it is not an issue.

**Pull request merged**
