### PR TITLE
Add timestamp during collection

### PR DESCRIPTION
**Pull request by ZikyHD**
When running the different artifact collections, it seemed interesting to have a view on the start time.

image

### CODE REVIEW

**Review by tclahr — CHANGES_REQUESTED** [review]
I would use the same timestamp format already used in uac.log.
`date "+%Y-%m-%d %H:%M:%S %z"`

**Comment by tclahr** [comment]
Hi,
Changes need to be merged into develop branch, not main/master. Can you re-submit this PR into develop branch? Thanks!

**Comment by ZikyHD** [comment]
Hi, 
The datetime format and the destination of the PR have been modified.
Btw I also take this opportunity to thank you for this great project :trophy:

**Review by tclahr — APPROVED** [review]

**Comment by tclahr** [comment]
Thank you for submitting it!

**Pull request merged**
